In [4]:
import numpy as np
import pandas as pd
import csv

## Create a file with business name, longitudinal, and latitude

In [5]:
write_file = "data/address_geo_dropme.csv"
with open(write_file, "w") as output:
    with open('data/geo_coords_sf.csv', 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            n = len(row)   # number of strings in a row. '2449', ' 23rd Street', ' Potrero Terrace', ...
            # below is for a line
            for i in range(2):  # iterate each string in a row. i is the position of a string within a row.
                row[i] = row[i].strip()  # strip off the white space in front
                if row[i].isdigit():  # this will enable to skip the business name in front
                    address = row[i] + row[i+1]
                    
                    if row[i+2].strip() == 'SF':
                        longitude = float(row[i+6])
                        latitude = float(row[i+7])
                    elif row[i+3].strip() == 'SF':
                        longitude = float(row[i+7])
                        latitude = float(row[i+8])
                       
                    output.write(address + ',' + str(longitude) + ',' + str(latitude) +  '\n')
                    break

In [6]:
# show the rows of geo_coords_sf.csv
with open('data/geo_coords_sf.csv', 'r') as f:
    reader = csv.reader(f)
    counter = 0
    for row in reader:
        print(row)
        counter += 1
        if counter > 5: break

['2449', ' 23rd Street', ' Potrero Terrace', ' SF', ' California', ' 94110', ' United States of America', '-122.403988857143', '37.7543434081633']
['909', ' Grant Avenue', ' Chinatown', ' SF', ' California', ' 94108', ' United States of America', '-122.406613368069', '37.795304999856']
['888', ' Stockton Street', ' Chinatown', ' SF', ' California', ' 94108', ' United States of America', '-122.407763040816', '37.7938858979592']
['LimÃ³n Rotisserie', ' 1001', ' South Van Ness Avenue', ' Mission District', ' SF', ' California', ' 94110', ' United States of America', '-122.4165149', '37.7570488']
["Domino's Pizza", ' 876', ' Geary Street', ' Tenderloin', ' SF', ' California', ' 94109', ' United States of America', '-122.4176924', '37.7862682']
['AT&T Park', ' 24', ' Willie Mays Plaza', ' South Beach', ' SF', ' California', ' 94107', ' United States of America', '-122.390267454256', '37.7786119']

In [7]:
# count the rows of address_geo.csv
with open('data/address_geo.csv', 'r') as f:
    reader = csv.reader(f)
    counter = 0
    for row in reader:
        counter += 1
        #print(row)
print(counter)

1474

## list of geo coords

In [8]:
df = pd.read_csv('data/ready4model_v2.csv')

In [9]:
mask = df['business_latitude'].isnull().values
mask.sum()

2231

In [10]:
df.head(20)

,Unnamed: 0,Unnamed: 0.1,business_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,...,short_inspect_date,short_violation_id,inspect_date,p1_3,p4_6,p7_9,p10_12,p13_18,p19_24,p25_36
0,0,0,1757,Dar Bar Pakistani/Indian Cusine,1412 Polk St,San Francisco,CA,94109,37.789784,-122.420455,...,20170928,103131,2017-09-28,0,0,5,0,0,6,5
1,1,1,4864,DRAGON CITY BAKERY & CAFE,2367 MISSION St,San Francisco,CA,94110,37.759174,-122.419066,...,20161206,103157,2016-12-06,0,6,0,0,5,5,3
2,2,2,79782,Deli 23,2449 23rd St,San Francisco,CA,94110,NaN,NaN,...,20160503,103120,2016-05-03,4,0,2,0,3,3,2
3,3,3,73840,L'acajou Bakery and Cafe,498 09th St Ste. C,San Francisco,CA,94103,NaN,NaN,...,20171207,103105,2017-12-07,0,5,0,0,6,0,0
4,4,4,76437,Sweetheart Cafe,909 Grant Ave,San Francisco,CA,94108,NaN,NaN,...,20160329,103113,2016-03-29,0,11,0,0,0,6,6
5,5,5,82123,Cafe New Honolulu,888 Stockton St,San Francisco,CA,94108,NaN,NaN,...,20171207,103131,2017-12-07,0,3,0,0,0,8,8
6,6,6,1146,Aux Delices Vietnam,2327 Polk St,San Francisco,CA,94109,37.798274,-122.422264,...,20180223,103103,2018-02-23,6,0,0,0,0,8,0
7,7,7,3838,CAFE PICARO,3120 16th St,San Francisco,CA,94103,37.764908,-122.422442,...,20180222,103142,2018-02-22,7,0,0,0,0,1,2
8,8,8,38929,Jelly Donut,3198 24th St,San Francisco,CA,94110,37.752439,-122.416250,...,20160114,103139,2016-01-14,0,0,7,0,3,4,6
9,9,9,81161,Limon Peruvian Rotisserie,1001 South Van Ness Ave,San Francisco,CA,94110,NaN,NaN,...,20160325,103149,2016-03-25,1,0,3,2,4,0,3
10,10,10,85781,Domino's #7764,876 Geary St,San Francisco,CA,94109,NaN,NaN,...,20160311,103124,2016-03-11,6,0,3,0,0,0,5
11,11,11,82880,Don Pablo,Off The Grid,San Francisco,CA,NaN,NaN,NaN,...,20160309,103148,2016-03-09,0,0,0,3,0,6,2
12,12,14,16441,Hawaiian Drive Inn,2600 San Bruno Ave,San Francisco,CA,94134,37.728718,-122.404101,...,20161206,103154,2016-12-06,0,6,0,0,5,3,0
13,13,16,2716,RED A BAKERY,634 CLEMENT St,San Francisco,CA,94118,37.782888,-122.466101,...,20160323,103131,2016-03-23,0,5,0,0,5,0,7
14,14,17,3165,HAN IL KWAN,1802 BALBOA St,San Francisco,CA,94121,37.776599,-122.478292,...,20170323,103149,2017-03-23,0,0,0,0,7,0,5
15,15,18,2995,CAFE ROCCO,1131 FOLSOM St,San Francisco,CA,94103,37.776127,-122.408602,...,20170809,103125,2017-08-09,0,0,5,0,1,0,6
16,16,20,64380,Michael Mina Restaurant,252 California St,San Francisco,CA,94111,37.793338,-122.399583,...,20160414,103154,2016-04-14,0,0,4,0,0,5,0
17,17,21,3594,CELIAS RESTAURANT,4019 JUDAH St,San Francisco,CA,94122,37.760423,-122.505209,...,20160330,103133,2016-03-30,0,0,0,0,0,0,4
18,18,24,5493,AT&T - (CART 17) DELI [145105],24 WILLIE MAYS PLAZA,San Francisco,CA,94107,NaN,NaN,...,20160814,103119,2016-08-14,0,0,0,0,0,2,0
19,19,25,69762,Chili House Inc.,726 Clement St,San Francisco,CA,94118,NaN,NaN,...,20160413,103133,2016-04-13,0,6,0,0,6,7,0

In [11]:
len(df)

5229

In [12]:
with open('data/address_geo.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        address = row[0]
        longitude = row[1]
        latitude = row[2]
        n = len(df)
        for idx in range(n):
            df_address = df.loc[idx,'business_address'].lower()
            if df_address[:10] == address.lower()[:10]:
                df.loc[idx,'business_longitude'] = longitude
                df.loc[idx,'business_latitude'] = latitude

In [18]:
df.head(20)

,Unnamed: 0,Unnamed: 0.1,business_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,...,short_inspect_date,short_violation_id,inspect_date,p1_3,p4_6,p7_9,p10_12,p13_18,p19_24,p25_36
0,0,0,1757,Dar Bar Pakistani/Indian Cusine,1412 Polk St,San Francisco,CA,94109,37.7898,-122.42,...,20170928,103131,2017-09-28,0,0,5,0,0,6,5
1,1,1,4864,DRAGON CITY BAKERY & CAFE,2367 MISSION St,San Francisco,CA,94110,37.7592,-122.419,...,20161206,103157,2016-12-06,0,6,0,0,5,5,3
2,2,2,79782,Deli 23,2449 23rd St,San Francisco,CA,94110,37.7543434081633,-122.403988857143,...,20160503,103120,2016-05-03,4,0,2,0,3,3,2
3,3,3,73840,L'acajou Bakery and Cafe,498 09th St Ste. C,San Francisco,CA,94103,NaN,NaN,...,20171207,103105,2017-12-07,0,5,0,0,6,0,0
4,4,4,76437,Sweetheart Cafe,909 Grant Ave,San Francisco,CA,94108,37.795304999856,-122.406613368069,...,20160329,103113,2016-03-29,0,11,0,0,0,6,6
5,5,5,82123,Cafe New Honolulu,888 Stockton St,San Francisco,CA,94108,37.7938858979592,-122.407763040816,...,20171207,103131,2017-12-07,0,3,0,0,0,8,8
6,6,6,1146,Aux Delices Vietnam,2327 Polk St,San Francisco,CA,94109,37.7983,-122.422,...,20180223,103103,2018-02-23,6,0,0,0,0,8,0
7,7,7,3838,CAFE PICARO,3120 16th St,San Francisco,CA,94103,37.7649,-122.422,...,20180222,103142,2018-02-22,7,0,0,0,0,1,2
8,8,8,38929,Jelly Donut,3198 24th St,San Francisco,CA,94110,37.7524,-122.416,...,20160114,103139,2016-01-14,0,0,7,0,3,4,6
9,9,9,81161,Limon Peruvian Rotisserie,1001 South Van Ness Ave,San Francisco,CA,94110,37.7570488,-122.4165149,...,20160325,103149,2016-03-25,1,0,3,2,4,0,3
10,10,10,85781,Domino's #7764,876 Geary St,San Francisco,CA,94109,37.7862682,-122.4176924,...,20160311,103124,2016-03-11,6,0,3,0,0,0,5
11,11,11,82880,Don Pablo,Off The Grid,San Francisco,CA,NaN,NaN,NaN,...,20160309,103148,2016-03-09,0,0,0,3,0,6,2
12,12,14,16441,Hawaiian Drive Inn,2600 San Bruno Ave,San Francisco,CA,94134,37.7287,-122.404,...,20161206,103154,2016-12-06,0,6,0,0,5,3,0
13,13,16,2716,RED A BAKERY,634 CLEMENT St,San Francisco,CA,94118,37.7829,-122.466,...,20160323,103131,2016-03-23,0,5,0,0,5,0,7
14,14,17,3165,HAN IL KWAN,1802 BALBOA St,San Francisco,CA,94121,37.7766,-122.478,...,20170323,103149,2017-03-23,0,0,0,0,7,0,5
15,15,18,2995,CAFE ROCCO,1131 FOLSOM St,San Francisco,CA,94103,37.7761,-122.409,...,20170809,103125,2017-08-09,0,0,5,0,1,0,6
16,16,20,64380,Michael Mina Restaurant,252 California St,San Francisco,CA,94111,37.7933,-122.4,...,20160414,103154,2016-04-14,0,0,4,0,0,5,0
17,17,21,3594,CELIAS RESTAURANT,4019 JUDAH St,San Francisco,CA,94122,37.7604,-122.505,...,20160330,103133,2016-03-30,0,0,0,0,0,0,4
18,18,24,5493,AT&T - (CART 17) DELI [145105],24 WILLIE MAYS PLAZA,San Francisco,CA,94107,37.7786119,-122.390267454256,...,20160814,103119,2016-08-14,0,0,0,0,0,2,0
19,19,25,69762,Chili House Inc.,726 Clement St,San Francisco,CA,94118,37.782915244898,-122.466924306122,...,20160413,103133,2016-04-13,0,6,0,0,6,7,0

In [14]:
# count of no geo coords
mask = df['business_latitude'].isnull().values

In [15]:
mask.sum()

742

In [16]:
df.count()

Unnamed: 0               5229
Unnamed: 0.1             5229
business_id              5229
business_name            5229
business_address         5229
business_city            5229
business_state           5229
business_postal_code     5070
business_latitude        4487
business_longitude       4487
business_location        2998
business_phone_number    1582
inspection_id            5229
inspection_date          5229
inspection_score         4808
inspection_type          5229
violation_id             5229
violation_description    5229
risk_category            5229
short_inspect_date       5229
short_violation_id       5229
inspect_date             5229
p1_3                     5229
p4_6                     5229
p7_9                     5229
p10_12                   5229
p13_18                   5229
p19_24                   5229
p25_36                   5229
dtype: int64

In [17]:
df.to_csv('data/first_round_geo_imported.csv')